receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:8080"

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

exporters:
  googlecloud:
    project: "mvn-sandbox-smsgw-yzhan" # Your Project ID
    metric:
      # This prefix puts metrics in a clean folder in Cloud Monitoring
      prefix: "custom.googleapis.com/opentelemetry/"
    # Traces are enabled by default

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [googlecloud]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [googlecloud]